apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: kong
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kong
    repoURL: https://charts.konghq.com
    targetRevision: 2.35.1
    helm:
      valueFiles:
      - my-gitops-repo/environments/dev/kong/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
